name: Push to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: npm install
      - run: npm run build --if-present
      - name: Copy server files
        run: mkdir dist/server ; cp -R server/*.js* dist/server/
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync dist s3://linkedinsight/linkedinsight --delete
